const INITIAL_DATA = 'INITIAL_DATA'

export const FETCH_INITIAL_DATA = `FETCH_${INITIAL_DATA}`
export const FULFILLED_INITIAL_DATA = `FULFILLED_${INITIAL_DATA}`
export const REJECT_INITIAL_DATA = `REJECT_${INITIAL_DATA}`
